### ISSUE TITLE
file missing 

### ISSUE THREAD

**Issue by faizanmalikmore** [simscape/Electric-Vehicle-Simscape#1]
Hello 
I try to open more information on different BEV components but error appear
File 'BEVModelMain.mlx' not found.

**Comment by JiteshJhaIN** [comment]
Hi, 
Thanks for reporting this issue, Is the issue with hyperlink in 'BEVBatterySizingMain.mlx'?

**Comment by JiteshJhaIN** [comment]
Have fixed the broken link.
